// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseMaterial", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "MaterialId")
                        .HasName("PK__CourseMaterial");

                    b.HasIndex("MaterialId");

                    b.ToTable("CourseMaterial", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            MaterialId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            MaterialId = 2
                        },
                        new
                        {
                            CourseId = 3,
                            MaterialId = 3
                        },
                        new
                        {
                            CourseId = 4,
                            MaterialId = 4
                        },
                        new
                        {
                            CourseId = 5,
                            MaterialId = 5
                        },
                        new
                        {
                            CourseId = 6,
                            MaterialId = 6
                        },
                        new
                        {
                            CourseId = 7,
                            MaterialId = 7
                        },
                        new
                        {
                            CourseId = 8,
                            MaterialId = 8
                        },
                        new
                        {
                            CourseId = 9,
                            MaterialId = 9
                        },
                        new
                        {
                            CourseId = 1,
                            MaterialId = 10
                        },
                        new
                        {
                            CourseId = 2,
                            MaterialId = 11
                        },
                        new
                        {
                            CourseId = 3,
                            MaterialId = 12
                        },
                        new
                        {
                            CourseId = 4,
                            MaterialId = 13
                        },
                        new
                        {
                            CourseId = 5,
                            MaterialId = 14
                        },
                        new
                        {
                            CourseId = 6,
                            MaterialId = 15
                        },
                        new
                        {
                            CourseId = 7,
                            MaterialId = 16
                        },
                        new
                        {
                            CourseId = 8,
                            MaterialId = 17
                        },
                        new
                        {
                            CourseId = 9,
                            MaterialId = 18
                        },
                        new
                        {
                            CourseId = 1,
                            MaterialId = 19
                        },
                        new
                        {
                            CourseId = 2,
                            MaterialId = 20
                        },
                        new
                        {
                            CourseId = 3,
                            MaterialId = 21
                        },
                        new
                        {
                            CourseId = 4,
                            MaterialId = 22
                        },
                        new
                        {
                            CourseId = 5,
                            MaterialId = 23
                        },
                        new
                        {
                            CourseId = 6,
                            MaterialId = 24
                        },
                        new
                        {
                            CourseId = 7,
                            MaterialId = 25
                        },
                        new
                        {
                            CourseId = 8,
                            MaterialId = 26
                        },
                        new
                        {
                            CourseId = 9,
                            MaterialId = 27
                        });
                });

            modelBuilder.Entity("CourseSkill", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "SkillId")
                        .HasName("PK__CourseSkill");

                    b.HasIndex("SkillId");

                    b.ToTable("CourseSkill", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            SkillId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            CourseId = 3,
                            SkillId = 1
                        },
                        new
                        {
                            CourseId = 3,
                            SkillId = 2
                        },
                        new
                        {
                            CourseId = 3,
                            SkillId = 3
                        },
                        new
                        {
                            CourseId = 4,
                            SkillId = 4
                        },
                        new
                        {
                            CourseId = 5,
                            SkillId = 4
                        },
                        new
                        {
                            CourseId = 5,
                            SkillId = 5
                        },
                        new
                        {
                            CourseId = 6,
                            SkillId = 4
                        },
                        new
                        {
                            CourseId = 6,
                            SkillId = 5
                        },
                        new
                        {
                            CourseId = 6,
                            SkillId = 6
                        },
                        new
                        {
                            CourseId = 7,
                            SkillId = 7
                        },
                        new
                        {
                            CourseId = 8,
                            SkillId = 7
                        },
                        new
                        {
                            CourseId = 8,
                            SkillId = 8
                        },
                        new
                        {
                            CourseId = 9,
                            SkillId = 7
                        },
                        new
                        {
                            CourseId = 9,
                            SkillId = 8
                        },
                        new
                        {
                            CourseId = 9,
                            SkillId = 9
                        });
                });

            modelBuilder.Entity("Domain.Common.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Materials");

                    b.ToTable("Materials");

                    b.HasDiscriminator<string>("Type").HasValue("Material");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Courses");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Description = "java script beginner course",
                            Title = "js-course(beginner)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Description = "java script intermadiate course",
                            Title = "js-course(intermadiate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Description = "java script master course",
                            Title = "js-course(master)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Description = "react beginner course",
                            Title = "react-course(beginner)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Description = "react intermadiate course",
                            Title = "react-course(intermadiate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Description = "react master course",
                            Title = "react-course(master)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Description = "c# beginner course",
                            Title = "c#-course(beginner)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Description = "c# intermadiate course",
                            Title = "c#-course(intermadiate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Description = "c# master course",
                            Title = "c#-course(naster)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Format", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormatType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Formats");

                    b.ToTable("Formats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            FormatType = "epub",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            FormatType = "pdf",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            FormatType = "docx",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            FormatType = "azw",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            FormatType = "txt",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Quality", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QualityType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Qualities");

                    b.ToTable("Qualities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            QualityType = "144p",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            QualityType = "240p",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            QualityType = "360p",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            QualityType = "480p",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            QualityType = "720p",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            QualityType = "1080p",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            QualityType = "1440p",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            QualityType = "2160p",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        });
                });

            modelBuilder.Entity("Domain.Entities.RoleGroup.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "administrator",
                            NormalizedName = "ADMINISTRATOR",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "teacher",
                            NormalizedName = "TEACHER",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "student",
                            NormalizedName = "STUDENT",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "guest",
                            NormalizedName = "GUEST",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        });
                });

            modelBuilder.Entity("Domain.Entities.RoleGroup.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Skills");

                    b.HasIndex(new[] { "Name" }, "UQ__Skills")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "js-beginner",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "js-intermediate",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "js-master",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "react-beginner",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "react-intermediate",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "react-master",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "c#-beginner",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "c#-intermediate",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Name = "c#-master",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__Users")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<decimal>("Progress")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserCourses");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCourses");
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserSkills");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Article", b =>
                {
                    b.HasBaseType("Domain.Common.Material");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasDiscriminator().HasValue("Article");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "js-article(beginner) ",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Link = "https://www.w3schools.com/js/default.asp"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "js-article(intermediate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Link = "https://www.w3schools.com/js/default.asp"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "js-article(master)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Link = "https://www.w3schools.com/js/default.asp"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "react-article(beginner)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Link = "https://www.w3schools.com/react/default.asp"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "react-article(intermediate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Link = "https://www.w3schools.com/react/default.asp"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "react-article(master)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Link = "https://www.w3schools.com/react/default.asp"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "c#-article(beginner)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Link = "https://www.w3schools.com/cs/index.php"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "c#-article(intermediate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Link = "https://www.w3schools.com/cs/index.php"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "c#-article(master)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Link = "https://www.w3schools.com/cs/index.php"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ebook", b =>
                {
                    b.HasBaseType("Domain.Common.Material");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FormatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("PageAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasIndex("FormatId");

                    b.HasDiscriminator().HasValue("Ebook");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "js-ebook(beginner)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Author = "david flanagan",
                            FormatId = 2,
                            PageAmount = 1093,
                            PublishedOn = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "js-ebook(intermediate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Author = "david herman",
                            FormatId = 2,
                            PageAmount = 228,
                            PublishedOn = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "js-ebook(master)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Author = "nicholas c.zakas",
                            FormatId = 3,
                            PageAmount = 960,
                            PublishedOn = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "react-ebook(beginner)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Author = "robin wieruch",
                            FormatId = 2,
                            PageAmount = 286,
                            PublishedOn = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "react-ebook(intermediate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Author = "adam boduch",
                            FormatId = 3,
                            PageAmount = 526,
                            PublishedOn = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "react-ebook(master)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Author = "carlos santana roldan",
                            FormatId = 3,
                            PageAmount = 394,
                            PublishedOn = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "c#-ebook(beginner)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Author = "r.b. whitaker",
                            FormatId = 1,
                            PageAmount = 406,
                            PublishedOn = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "c#-ebook(intermediate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Author = "ian griffiths",
                            FormatId = 2,
                            PageAmount = 778,
                            PublishedOn = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "c#-ebook(master)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Author = "mark j.price",
                            FormatId = 2,
                            PageAmount = 826,
                            PublishedOn = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Video", b =>
                {
                    b.HasBaseType("Domain.Common.Material");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("QualityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasIndex("QualityId");

                    b.HasDiscriminator().HasValue("Video");

                    b.HasData(
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "js-video(beginner)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Duration = new TimeOnly(1, 30, 25),
                            QualityId = 5
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "js-video(intermediate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Duration = new TimeOnly(1, 30, 25),
                            QualityId = 6
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "js-video(master)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Duration = new TimeOnly(1, 30, 25),
                            QualityId = 6
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "react-video(beginner)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Duration = new TimeOnly(1, 30, 25),
                            QualityId = 6
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "react-video(intermediate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Duration = new TimeOnly(1, 30, 25),
                            QualityId = 6
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "react-video(master)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Duration = new TimeOnly(1, 30, 25),
                            QualityId = 6
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "c#-video(beginner)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Duration = new TimeOnly(1, 30, 25),
                            QualityId = 6
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "c#-video(intermediate)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Duration = new TimeOnly(1, 30, 25),
                            QualityId = 6
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Title = "c#-video(master)",
                            UpdatedAt = new DateTime(2024, 12, 20, 16, 3, 14, 174, DateTimeKind.Utc).AddTicks(7870),
                            Duration = new TimeOnly(1, 30, 25),
                            QualityId = 6
                        });
                });

            modelBuilder.Entity("CourseMaterial", b =>
                {
                    b.HasOne("Domain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CourseMaterial__Course");

                    b.HasOne("Domain.Common.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CourseMaterial__Material");
                });

            modelBuilder.Entity("CourseSkill", b =>
                {
                    b.HasOne("Domain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CourseSkill__Course");

                    b.HasOne("Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CourseSkill__Skill");
                });

            modelBuilder.Entity("Domain.Entities.RoleGroup.RoleClaim", b =>
                {
                    b.HasOne("Domain.Entities.RoleGroup.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserClaim", b =>
                {
                    b.HasOne("Domain.Entities.UserGroup.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserCourse", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__UserCourses__CourseId");

                    b.HasOne("Domain.Entities.UserGroup.User", "User")
                        .WithMany("UserCourses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserCourses__UserId");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserLogin", b =>
                {
                    b.HasOne("Domain.Entities.UserGroup.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.RoleGroup.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.UserGroup.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserSkill", b =>
                {
                    b.HasOne("Domain.Entities.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__UserSkills__SkillId");

                    b.HasOne("Domain.Entities.UserGroup.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserSkills__UserId");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.UserToken", b =>
                {
                    b.HasOne("Domain.Entities.UserGroup.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Ebook", b =>
                {
                    b.HasOne("Domain.Entities.Format", "Format")
                        .WithMany("Ebooks")
                        .HasForeignKey("FormatId")
                        .IsRequired()
                        .HasConstraintName("FK__EBooks__FormatId");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("Domain.Entities.Video", b =>
                {
                    b.HasOne("Domain.Entities.Quality", "Quality")
                        .WithMany("Videos")
                        .HasForeignKey("QualityId")
                        .IsRequired()
                        .HasConstraintName("FK__Videos__QualityId");

                    b.Navigation("Quality");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("Domain.Entities.Format", b =>
                {
                    b.Navigation("Ebooks");
                });

            modelBuilder.Entity("Domain.Entities.Quality", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Domain.Entities.RoleGroup.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("Domain.Entities.UserGroup.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Tokens");

                    b.Navigation("UserCourses");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
